# Generated by Django 4.0 on 2021-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Prosze podać tytuł', max_length=40, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('realese_date', models.DateField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('iko', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('metacritick_rating', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=4, null=True)),
                ('platform', models.TextField(default='PC', max_length=100, null=True)),
            ],
        ),
    ]
